// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/global/other/animateList.vue')['default']
    Crumbs: typeof import('./../src/components/global/other/crumbs.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Historylink: typeof import('./../src/components/admin/historylink.vue')['default']
    Meditor: typeof import('./../src/components/editor/markdown/meditor.vue')['default']
    Memu: typeof import('./../src/components/admin/memu.vue')['default']
    Navbar: typeof import('./../src/components/admin/navbar.vue')['default']
    Notice: typeof import('./../src/components/global/other/notice.vue')['default']
    QlButton: typeof import('./../src/components/global/form/ql-button.vue')['default']
    QlInput: typeof import('./../src/components/global/form/ql-input.vue')['default']
    QlLink: typeof import('./../src/components/global/form/ql-link.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Weditor: typeof import('./../src/components/editor/wangEditor/weditor.vue')['default']
  }
}
